#include "Led.h"
#include "MKL46Z4.h"

void LED_Init(void){
    SIM->SCGC5 |= SIM_SCGC5_PORTD_MASK | SIM_SCGC5_PORTE_MASK;
    RED_LED_GPIO->PDDR |= RED_LED_MASK;
    GREEN_LED_GPIO->PDDR |= GREEN_LED_MASK;
    PORTE->PCR[RED_LED_PIN] |= PORT_PCR_MUX(1);
    PORTD->PCR[GREEN_LED_PIN] |= PORT_PCR_MUX(1);
    RED_LED_OFF();
    GREEN_LED_OFF();
}

void RED_LED_Init(void){
    SIM->SCGC5 |= SIM_SCGC5_PORTE_MASK;
    PORTD->PCR[5] |= PORT_PCR_MUX(1);
    RED_LED_GPIO->PDDR |= RED_LED_MASK;
    RED_LED_OFF();
}

void GREEN_LED_Init(void){
    SIM->SCGC5 |= SIM_SCGC5_PORTD_MASK;
    PORTD->PCR[5] |= PORT_PCR_MUX(1);
    GREEN_LED_GPIO->PDDR |= GREEN_LED_MASK;
    GREEN_LED_OFF();
}

